### ISSUE TITLE
Node grouping (modules) checklist

### ISSUE THREAD

**Issue by maximecb** [maximecb/noisecraft#70]
A feature that I've been slowly working towards is the ability to group multiple nodes into a user-created module. I think this can unlock a lot of potential for this app because it will help manage the complexity in larger projects, and it will allow people to create custom modules for sounds and sound effects. Modules will also be copyable between projects, so you can imagine something like drum sounds being reused across projects.

This is a list of tasks that need to be completed for this new feature to come together:
- [x] GroupNodes action
- [x] Ability to show an error message in the editor, `errorDialog()`
- [x] Remove restriction that there can only be a single `Notes` node
- [ ] #15
- [ ] #19
- [ ] Show error message when trying to group nodes that aren't groupable (i.e. sequencers, scopes)
- [ ] Test that modules interact properly with copy and paste
- [ ] Support for modules in `validateProject()`

**Comment by tricky-labyrinth** [comment]
Any progress on this? Not sure if just the issue hasn't been updated yet.

**Comment by maximecb** [comment]
Hi there. I've completed some of the work but haven't progressed since due to real life challenges. If you would like to work on this, I can explain the plan in more details or answer questions to help you get started.
